### ISSUE TITLE
Fully Support version format 16395

### ISSUE THREAD

**Issue by num0005** [Project-Cartographer/H2V-Blender-Animation-Exporter#15]
16395 can optionally include extra transforms at the end of the file, one for each `transform count` in the header. Currently the exporter is hard-coded to not include this. I'm not exactly sure how this is used, maybe some sort of global transform for all nodes? Seems to the exact same format as other transforms.

It would be good to fully support 16395 considering it's version that h2 was actually meant to use.

**Comment by num0005** [comment]
<@180351358149328896> <@332968312373903360>

**Comment by General-101** [comment]
Label unknown as biped controller data. Exact purpose isn't known.

**Comment by General-101** [comment]
Could possibly be a 3DS Max thing?

https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/3DSMax/files/GUID-3E536043-9F91-45E3-ACA4-EB0799C835AF-htm.html

**Comment by General-101** [comment]
![image](https://cdn.discordapp.com/attachments/339567029550055424/683001236114636804/unknown.png)

Explanation from a Discord I got for what this could have been

> biped was the older setup for bones which were supposed to basically give 3DS Max the equivalent of modern day Maya's animation tools
> but it fell flat because the only good thing it has was easier importing of motion capture data
> which became obsolete once you could import baked animation without any issue

This is pretty pointless. The animation exporter can be considered complete with this.
